version: '3.8'

services:
  c64:
    build:
      context: .
      dockerfile: docker/Dockerfile.c64
    image: code198x/c64:latest
    container_name: code198x-c64
    volumes:
      - ./workspace/c64:/workspace/projects
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
    working_dir: /workspace/projects
    stdin_open: true
    tty: true
    networks:
      - code198x

  spectrum:
    build:
      context: .
      dockerfile: docker/Dockerfile.spectrum
    image: code198x/spectrum:latest
    container_name: code198x-spectrum
    volumes:
      - ./workspace/spectrum:/workspace/projects
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
    working_dir: /workspace/projects
    stdin_open: true
    tty: true
    networks:
      - code198x

  amiga:
    build:
      context: .
      dockerfile: docker/Dockerfile.amiga
    image: code198x/amiga:latest
    container_name: code198x-amiga
    volumes:
      - ./workspace/amiga:/workspace/projects
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
    working_dir: /workspace/projects
    stdin_open: true
    tty: true
    networks:
      - code198x

  nes:
    build:
      context: .
      dockerfile: docker/Dockerfile.nes
    image: code198x/nes:latest
    container_name: code198x-nes
    volumes:
      - ./workspace/nes:/workspace/projects
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
    working_dir: /workspace/projects
    stdin_open: true
    tty: true
    networks:
      - code198x

  # All-in-one development environment
  all:
    build:
      context: .
      dockerfile: docker/Dockerfile.all
    image: code198x/all:latest
    container_name: code198x-all
    volumes:
      - ./workspace:/workspace/projects
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
    working_dir: /workspace/projects
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"  # For web-based tools
    networks:
      - code198x

networks:
  code198x:
    driver: bridge

volumes:
  workspace:
    driver: local