name: Build System Image

on:
  workflow_call:
    inputs:
      system-name:
        required: true
        type: string
        description: 'System name (e.g., commodore-64)'
      display-name:
        required: true
        type: string
        description: 'Display name for the system (e.g., Commodore 64)'
      test-command:
        required: false
        type: string
        default: '--help'
        description: 'Command to test the image'
      version-tag:
        required: false
        type: string
        description: 'Specific version tag for release builds (e.g., v1.0.0)'
    secrets:
      DOCKER_USERNAME:
        required: false
      DOCKER_TOKEN:
        required: false

env:
  DOCKER_ORG: code198x
  GHCR_ORG: ghcr.io/code198x
  # Improve Docker build performance and reliability
  DOCKER_BUILDKIT: 1
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1
  # Registry rate limiting protection
  REGISTRY_RETRY_ATTEMPTS: 3
  REGISTRY_RETRY_DELAY: 30

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: ${{ inputs.display-name }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check for Docker Hub credentials
        id: check-docker-creds
        run: |
          if [ -n "${{ secrets.DOCKER_USERNAME }}" ] && [ -n "${{ secrets.DOCKER_TOKEN }}" ]; then
            echo "has-creds=true" >> $GITHUB_OUTPUT
          else
            echo "has-creds=false" >> $GITHUB_OUTPUT
          fi

      - name: Log in to Docker Hub
        if: steps.check-docker-creds.outputs.has-creds == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.GHCR_ORG }}/${{ inputs.system-name }}
            ${{ steps.check-docker-creds.outputs.has-creds == 'true' && format('{0}/{1}', env.DOCKER_ORG, inputs.system-name) || '' }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-,enable=${{ inputs.version-tag == '' }}
            type=raw,value=${{ inputs.version-tag }},enable=${{ inputs.version-tag != '' }}

      - name: Build and push ${{ inputs.display-name }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ endsWith(inputs.system-name, '-base') && format('./base-images/{0}/Dockerfile', inputs.system-name) || format('./systems/{0}/Dockerfile', inputs.system-name) }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test ${{ inputs.display-name }} image
        run: |
          echo "🔍 Testing ${{ inputs.display-name }} image..."
          docker run --rm ${{ env.GHCR_ORG }}/${{ inputs.system-name }}:latest ${{ inputs.test-command }} || \
          echo "ℹ️ Test command may not be supported"